apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-buildpack-node-app-deployment
  labels:
    app: my-buildpack-node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-buildpack-node-app
  template:
    metadata:
      labels:
        app: my-buildpack-node-app
    spec:
      containers:
      - name: my-buildpack-node-app
        image: us-west1-docker.pkg.dev/gke-playground-477517/buildpack/my-node-app:v1
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: DEPLOY_TYPE
          value: "buildpack"
---
apiVersion: v1
kind: Service
metadata:
  name: my-buildpack-node-app-lb
spec:
  type: LoadBalancer
  selector:
    app: my-buildpack-node-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080